version: '3.4'

services:
  grafana:
    image: grafana/grafana:6.0.0
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
      - D:\dockervolumes\grafana:/var/lib/grafana

  pmserver:
    image: dev/productionmonitoring
    container_name: pmserver
    build:
      context: .
      dockerfile: ProductionMonitoring.WebHost/Dockerfile

  pmmeasure:
    image: dev/productionmonitoring
    container_name: pmmeasure
    environment:
      - APP=measure
    build:
      context: .
      dockerfile: ProductionMonitoring.WebHost/Dockerfile
